Vagrant.configure("2") do |config|
    
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end

    config.vm.define "admin" do |machine2|
      machine2.vm.box = "generic/rocky9"
      machine2.vm.hostname = "admin"
      machine2.vm.network "private_network", ip: "10.3.1.12"
  
      # Configuration du provisionnement avec Ansible
      machine2.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/dbadmin.yml"
      end
    end
    
    config.vm.define "db" do |machine1|
      machine1.vm.box = "generic/rocky9"
      machine1.vm.hostname = "db"
      machine1.vm.network "private_network", ip: "10.3.1.11"
  
      # Configuration du provisionnement avec Ansible
      machine1.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/db.yml"
      end
    end
  

  
    config.vm.define "machine3" do |machine3|
      machine3.vm.box = "generic/rocky9"
      machine3.vm.hostname = "machine3"
      machine3.vm.network "private_network", ip: "10.3.1.13"
  
      # # Configuration du provisionnement avec Ansible
      # machine3.vm.provision "ansible" do |ansible|
      #   ansible.playbook = "ansible/pop_smoke.yml"
      # end
    end
  
  end
  